### PR TITLE
Relaxing Test File Pattern

### PR DESCRIPTION
**Pull request by ameent**
The new pattern includes all extensions so that files written in TypeScript
and other languages are picked up as well.

### CODE REVIEW

**Comment by ameent** [comment]
I have no idea how to test this. Instruction on this in the README.md file would be useful. Hope this commit helps.

**Comment by rissem** [comment]
First of all, thanks! The only thing I'd be concerned about is that non-test files (like a test README or a .gitignore) could throw things off. 

I added some instructions for how to test mocha as a local package to the README. Could you make sure your changes work with LIveScript, and work with extra non-test files?

**Comment by ameent** [comment]
Thanks Michael. I'm on my phone now so haven't seen the instructions you
have put up yet. I'll try to get back to you on this with testing results
by Monday EOD

**Comment by rissem** [comment]
Thanks for verifying @rdickert

**Pull request merged**
