### PR TITLE
Fix a variable access issue when velocity is not enabled(velocity=0)

### PR DESCRIPTION
**Pull request by serut**
I don't know how to add this pull request to the last one (if it's possible) so I created a new one.
Thanks,

### CODE REVIEW

**Comment by serut** [comment]
This issue is still persisting, can you please accept this pull request ? It happens when you run a project with VELOCITY=0
error-package-mad-eye

**Comment by firrae** [comment]
We just ran into this exact same issue, is there an ETA on when this might be pulled in so we can update?

**Comment by davidworkman9** [comment]
@rissem +1

**Comment by firrae** [comment]
Thank you @rissem

**Comment by davidworkman9** [comment]
Can you push this to atmosphere please?

**Comment by firrae** [comment]
+1 @rissem, doesn't seem it was updated on Atmosphere.

**Comment by serut** [comment]
@rissem, can you update the version of this package from 0.6.5 to 0.6.6 to let us get the fix ?

**Comment by rissem** [comment]
Published to atmosphere now. Thanks for letting me know it was unpublished.

**Comment by firrae** [comment]
Thanks a bunch @serut and @rissem, this seems to have solved my problem!

**Pull request merged**
